### ISSUE TITLE
Recognise sxhkd file

### ISSUE THREAD

**Issue by harishnkr** [RaafatTurki/tree-sitter-sxhkdrc#1]
Hey there. Thank you for the plugin. i tried installing via TSinstall and it is installed but neovim does not reconise my file as sxhkdrc. What else should I do to enable it in the sxhkdrc buffer?

**Comment by RaafatTurki** [comment]
Hi, thanks!
Yes nvim ft detection doesn't automatically detect sxhkdrc files like other languages.

add this to your config to make it auto detect it
```lua
vim.cmd [[au BufEnter sxhkdrc,*.sxhkdrc set ft=sxhkdrc]]
```

bonus:
add this too to make nvim understand how to do commenting inside sxhkdrc files
```lua
vim.cmd [[au FileType sxhkdrc setlocal commentstring=#%s]]
```

**Comment by harishnkr** [comment]
Thanks. I did look through your venom nvim config and got a rough idea, but it didnt work because of the way my own config was set up. It works after some fixing. Another method that did work was to add `# vim:ft=sxhkdrc ` line above sxhkrd file which changes its filetype. Nonetheless, thank you for the tree sitter plugin as well your help regarding filetypes.  I enjoy your contributions. Have a great week.
